// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6UbRVy8kNSmKq4m4Px8dTw6sxBKaQOI0',
    appId: '1:506962201306:web:2469460c28677cd1f673e3',
    messagingSenderId: '506962201306',
    projectId: 'my-downloader1',
    authDomain: 'my-downloader1.firebaseapp.com',
    storageBucket: 'my-downloader1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGlRYh9d6Ngf6AhL57SaWZ0jdiLfUkNk', // 匹配
    appId: '1:947261366358:android:37ffa7029e6a67942c9bf7', // 需要修改为这个新值
    messagingSenderId: '947261366358', // 匹配
    projectId: 'tksaver-afb58',
    storageBucket: 'tksaver-afb58.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN_55vRXcQNprWFTUn-9csrnrTG4ro-9Q',
    appId: '1:506962201306:ios:b9e135d8998c1c04f673e3',
    messagingSenderId: '506962201306',
    projectId: 'my-downloader1',
    storageBucket: 'my-downloader1.firebasestorage.app',
    iosBundleId: 'com.example.analyzeVideoUrlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN_55vRXcQNprWFTUn-9csrnrTG4ro-9Q',
    appId: '1:506962201306:ios:b9e135d8998c1c04f673e3',
    messagingSenderId: '506962201306',
    projectId: 'my-downloader1',
    storageBucket: 'my-downloader1.firebasestorage.app',
    iosBundleId: 'com.example.analyzeVideoUrlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6UbRVy8kNSmKq4m4Px8dTw6sxBKaQOI0',
    appId: '1:506962201306:web:982a5d663e220518f673e3',
    messagingSenderId: '506962201306',
    projectId: 'my-downloader1',
    authDomain: 'my-downloader1.firebaseapp.com',
    storageBucket: 'my-downloader1.firebasestorage.app',
  );
}
