name: app_images_action_image_pickers
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_image_kit:
    path: ../flutter_image_kit/
  flutter_theme_helper:
    path: ../flutter_theme_helper/
  fluro: any
  # 图片数据
  flutter_image_process:
    path: ../flutter_image_process/
  # 图片列表
  flutter_images_action_list:
    path: ../flutter_images_action_list/

  flutter_player_ui:
    path: ../flutter_player_ui/
  
  # 图片选择
#  image_pickers: any
  # wechat_assets_picker: any
  wechat_assets_picker: ^8.2.0 # 7.3.0(5.13)
  wechat_camera_picker: ^3.6.5 # 3.2.0+1(5.13)
  # 图片压缩
  flutter_image_compress: any
  video_compress: any
  video_thumbnail: ^0.5.3
  video_player: ^2.4.7
  # 为了使用 actionSheet
  flutter_overlay_kit:
    path: ../flutter_overlay_kit/

  # tsdemo_player:
  #   path: ../null/tsdemo_player/
#  ffmpeg_kit_flutter_video: 4.5.1-LTS
  path_provider: ^2.0.11
  flutter_easyloading: ^3.0.5
  dio: ^4.0.0
  flutter_effect_kit:
    path: ../flutter_effect_kit/
  extended_image: any

  flutter_media_browser:
    path: ../null/flutter_media_browser/

  app_network:
    path: ../app_network/
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
