name: app_devtool_framework
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: any

  app_global_config:
    path: ../app_global_config/
    
  app_network:
    path: ../app_network/
  flutter_network_kit:
    path: ../flutter_network_kit/

  app_environment:
    path: ../app_environment/
  flutter_environment_base:
    path: ../flutter_environment_base/

  flutter_theme_helper:
    path: ../flutter_theme_helper/
  flutter_baseui_kit:
    path: ../flutter_baseui_kit/
  flutter_overlay_kit:
    path: ../flutter_overlay_kit/

  app_updateversion_kit:
    path: ../app_updateversion_kit/
  flutter_updateversion_kit:
    path: ../flutter_updateversion_kit/

  app_service_user:
    path: ../app_service_user/
  
  path_provider: any

  flutter_log_with_env:
    path: ../flutter_log_with_env/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/html/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
